name: Build and Test

on: 
  push:
    branches:
      - master
  repository_dispatch:
    types: [build]
  workflow_dispatch:

  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #     - cron:  '0 7 * * *'
  # repository_dispatch:
  #   types: [publish-packages]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [windows-latest, ubuntu-latest, macos-latest]
    #     chain: ['XDS', 'CITY']
    #     include:
    #       - os: windows-latest
    #         extension: ".zip"
    #         runtime: "win-x64"
    #       - os: ubuntu-latest
    #         extension: ".tar.gz"
    #         runtime: "linux-x64"
    #       - os: macos-latest
    #         runtime: "osx-x64"
    #         extension: ".zip"
    steps:

    - uses: actions/checkout@v2

    - name: Setup Node.js (12.x)
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Variables
      run: |
        echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      shell: bash

    - name: Nuget Pack
      run: dotnet pack --configuration Release --output "${{github.workspace}}/package/" src/SillyUselessPackage.sln -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: "${{github.workspace}}/package/"
        draft: true
        prerelease: false
        body: ''
        name: "SillyUselessPackage ${{env.VERSION}}"
        tag: ${{env.VERSION}}

#    - uses: actions/download-artifact@v2

    # - uses: robinraju/release-downloader@v1
    #   with:
    #     repository: "sondreb/playground"
    #     latest: true
    #     tarBall: true
    #     zipBall: true

    # - name: Download Release Asset
    #   id: download_release_asset
    #   uses: i3h/download-release-asset@v1
    #   with:
    #     owner: sondreb
    #     repo: playground
    #     tag: latest
    
    # - name: Download CLI
    #   uses: Legion2/download-release-action@v2.1.0
    #   with:
    #     repository: sondreb/playground
    #     tag: '0.0.1'
    #     path: downloads
    #     file: OpenWhisk_CLI-0.10.0-incubating-all.tgz

#    - name: Display structure of downloaded files
#      run: ls -R

    # - name: Download Release Assets
    #   run: |
    #     curl -s -L -o release.tar.gz https://github.com/block-core/blockcore-nodes/releases/download/1.0.16/CITY-1.0.16-linux-x64.tar.gz
    #     mkdir release
    #     tar -xvf release.tar.gz -C release

    # - name: Build the Docker container image
    #   run: docker build -f "./src/Project/Dockerfile" -t blockcore/tipbot:latest "."




      #run: docker build -f "./src/Project/Dockerfile" -t blockcore/tipbot:latest -t blockcore/tipbot:${{ github.event.release.tag_name }} "."

    # - name: Login and Push to Docker Registry
    #   run: |
    #     docker login -u "sondreb" -p "${{secrets.DockerHubSecret}}"
    #     docker push blockcore/indexer


    # - uses: actions/checkout@v1
    #   name: Checkout

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.101

    # - name: Variables
    #   run: |
    #     echo "::set-env name=RELEASE_RUNTIME::${{ matrix.runtime }}"
    #     echo "::set-env name=RELEASE_CHAIN::${{ matrix.chain }}"
    #     echo ${{ matrix.chain }}
    #     echo ${{ matrix.os }}
