name: Build and Test

on: 
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #     - cron:  '0 7 * * *'
  # repository_dispatch:
  #   types: [publish-packages]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [windows-latest, ubuntu-latest, macos-latest]
    #     chain: ['XDS', 'CITY']
    #     include:
    #       - os: windows-latest
    #         extension: ".zip"
    #         runtime: "win-x64"
    #       - os: ubuntu-latest
    #         extension: ".tar.gz"
    #         runtime: "linux-x64"
    #       - os: macos-latest
    #         runtime: "osx-x64"
    #         extension: ".zip"
    steps:

    - uses: actions/checkout@v2

#    - uses: actions/download-artifact@v2

    # - uses: robinraju/release-downloader@v1
    #   with:
    #     repository: "sondreb/playground"
    #     latest: true
    #     tarBall: true
    #     zipBall: true

    # - name: Download Release Asset
    #   id: download_release_asset
    #   uses: i3h/download-release-asset@v1
    #   with:
    #     owner: sondreb
    #     repo: playground
    #     tag: latest
    
    # - name: Download CLI
    #   uses: Legion2/download-release-action@v2.1.0
    #   with:
    #     repository: sondreb/playground
    #     tag: '0.0.1'
    #     path: downloads
    #     file: OpenWhisk_CLI-0.10.0-incubating-all.tgz

    - name: Download Release Assets
      shell: bash
      run: |
        curl -s -L https://github.com/sondreb/playground/releases/download/0.0.1/Blockcore.Features.BlockStore.1.0.13.nupkg
        tar -xvz -C .

    - name: Display structure of downloaded files
      run: ls -R

    # - uses: actions/checkout@v1
    #   name: Checkout

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.101

    # - name: Variables
    #   run: |
    #     echo "::set-env name=RELEASE_RUNTIME::${{ matrix.runtime }}"
    #     echo "::set-env name=RELEASE_CHAIN::${{ matrix.chain }}"
    #     echo ${{ matrix.chain }}
    #     echo ${{ matrix.os }}
